/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DisplayImage { 
    filePath?: string;
    readonly url?: string;
    readonly thumbnailUrl?: string;
    directoryName?: string;
    fileName?: string;
    isResized?: boolean;
    resizedFilePath?: string;
    thumbnailImagePath?: string;
    backgroundCover?: boolean;
    isResizing?: boolean;
}
